servos:
  pan:
    pin: 17
    min_angle: 0
    max_angle: 180
    min_pulse_width: 0.0005
    max_pulse_width: 0.0024
    neutral: 0.0
  tilt:
    pin: 27
    min_angle: 0
    max_angle: 180
    min_pulse_width: 0.0005
    max_pulse_width: 0.0024
    neutral: 0.0